### ISSUE TITLE
Provide settings to disable `webpack` or `rollup`

### ISSUE THREAD

**Issue by appsforartists** [TrySound/rollup-plugin-size-snapshot#25]
A crash in `treeshakeWithWebpack` is blocking https://github.com/cssinjs/jss/pull/936#discussion_r241926730.  An easy workaround would be to disable Webpack until #24 is fixed.  Unfortunately, there isn't currently that level of granularity in the settings.

**Comment by TrySound** [comment]
Shouldn't be necessary anymore.
