### ISSUE TITLE
Usage with rollup 1.0 errors out

### ISSUE THREAD

**Issue by mohsinulhaq** [TrySound/rollup-plugin-size-snapshot#26]
[!] (size-snapshot plugin) TypeError: Cannot read property 'length' of undefined TypeError: Cannot read property 'length' of undefined     at then.then.then.result (rollup-plugin-size-snapshot/dist/treeshakeWithRollup.js:75:25)

**Comment by pascalduez** [comment]
Reproducible with [this repo](https://github.com/pascalduez/react-module-boilerplate) if needed.

`result` seem to have this shape now `{ output: [ { code: '...' } ] }`.

**Comment by mohsinulhaq** [comment]
awesome 👍
