### ISSUE TITLE
Does not work with output.dir

### ISSUE THREAD

**Issue by detj** [TrySound/rollup-plugin-size-snapshot#29]
Expects `outputOptions.file` option to be set, but Rollup allows you to set `outputOptions.dir` too, in which case, `outputOptions.file` will be _undefined_.

https://github.com/TrySound/rollup-plugin-size-snapshot/blob/b86daaa0d7f0077fd02d50cdab14ddef6500b045/src/index.js#L74

Can this work without `output.file`? I suppose the file path/name has to be inferred somehow.

**Comment by agats** [comment]
+1 I'm running in this exact issue.

@TrySound Would it be fair to use `outputOptions.dir` if `outputOptions.file` is _undefined_?

**Comment by m59peacemaker** [comment]
Would a PR to support specifying the file as a plguin option be accepted?

```js
sizeSnapshot({ file: './build/my-entrypoint.js' })
```

**Comment by AshishMadaan** [comment]
+1 facing the same issue.
@TrySound when can we expect this to get fixed?

**Comment by TrySound** [comment]
Fixed in the new version
