### ISSUE TITLE
Provide ability to update snapshot

### ISSUE THREAD

**Issue by kylemh** [TrySound/rollup-plugin-size-snapshot#33]
Currently, if there's a desired size mis-match, I'm required to:
- delete the file
- delete `{ matchSnapshot: true }` from plugin config
- create build (new snapshot defined)
- re-add `{ matchSnapshot: true }` to plugin config

This feels like it can be improved.

**Comment by TrySound** [comment]
I usually set matchSnapshot to true only in ci

**Comment by kylemh** [comment]
Ah I see. That makes more sense. Perhaps some tiny documentation reflecting that then? The naming of the variable indicated to me that it should always be true.

**Comment by TrySound** [comment]
Do you want to send a PR with clarification?
