### ISSUE TITLE
Fill release notes

### ISSUE THREAD

**Issue by dmtrKovalenko** [TrySound/rollup-plugin-size-snapshot#44]
This package is not stable and there is no release notes for version. So we cannot upgrade the package version starting from 0.11. 

Moreover there is breaking change. It just doesn't work :) 
https://github.com/mui-org/material-ui-pickers/pull/1828

**Comment by TrySound** [comment]
The bug in your config. Replace plugin is not installed in pickers. Looks like before it used the one from size-snapshot. Stupid node_modules resolve algorithm!
https://github.com/mui-org/material-ui-pickers/blob/next/lib/rollup.config.js#L7

**Comment by dmtrKovalenko** [comment]
Thanks, but still release notes are useful! 
:)

**Comment by TrySound** [comment]
https://github.com/TrySound/rollup-plugin-size-snapshot/releases/tag/v0.12.0
