### ISSUE TITLE
Add fuzzy option for check

### ISSUE THREAD

**Issue by alexreardon** [TrySound/rollup-plugin-size-snapshot#6]
Right now `updateSnapshot` is used to avoid creating a snapshot and run a test instead.

Proposal:

Rename to `testSnapshotSize` (or something similar) to indicate that this is a validation step.

Also, can there also be an option to allow for a threshold of difference when testing against the current snapshot? Use case:

- I want to bump master on a branch
- I no longer satisfy the snapshot

I think it would be good to have an option to allow for a fuzzy threshold of difference between the current snapshot and the new one. Eg you could pass in that you would allow a 5% difference. This is purely to support merges from master.

Thoughts?

**Comment by TrySound** [comment]
Yeah, I think `threshold` is good option. What do you think about `matchSnapshot` in symmetry to jest?

**Comment by alexreardon** [comment]
Sounds good to me

**Comment by TrySound** [comment]
Published 0.4.0 with `matchSnapshot`. Will add threshold option in a couple days.

**Comment by TrySound** [comment]
Added fuzzy threshold in [v0.5.0](https://github.com/TrySound/rollup-plugin-size-snapshot/releases/tag/v0.5.0)
